### ISSUE TITLE
Attribute error when using serializer data in post_create

### ISSUE THREAD

**Issue by timlacroix** [tomchristie/django-rest-framework#2560]
Hey,

I have a HyperLinkedModelSerializer. To create it I need to check whether some field in serializer.data matches the request user.
I do this in post_create in my list view (generics.ListCreateAPIView).

Here is my exact perform_create :
```python
def perform_create(self, serializer):
        if not (self.request.user.username == serializer.data['username']):
            raise PermissionDenied()
        serializer.save()
```
And the traceback : 
```
Traceback (most recent call last):
  File "python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "python2.7/site-packages/rest_framework/generics.py", line 314, in post
    return self.create(request, *args, **kwargs)
  File "python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "backend/api_views.py", line 50, in perform_create
    if not (self.request.user.username == serializer.data['username']):
  File "python2.7/site-packages/rest_framework/serializers.py", line 463, in data
    ret = super(Serializer, self).data
  File "python2.7/site-packages/rest_framework/serializers.py", line 214, in data
    self._data = self.to_representation(self.validated_data)
  File "python2.7/site-packages/rest_framework/serializers.py", line 432, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "python2.7/site-packages/rest_framework/relations.py", line 257, in to_representation
    return self.get_url(value, self.view_name, request, format)
  File "python2.7/site-packages/rest_framework/relations.py", line 200, in get_url
    if obj.pk is None:
AttributeError: 'OrderedDict' object has no attribute 'pk'
```
The error seems to come from trying to create the url field when the object hasn't been created yet ... But I'm a total n00b with django-rest-framework so ... 

Thanks for your help,

Timothée Lacroix

**Comment by jpadilla** [comment]
The [discussion group](https://groups.google.com/forum/m/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. You'd also want to provide more information, like what DRF version you're using, and any other code that might give better context on what you're doing and help others help you out. Thanks!
