### ISSUE TITLE
obtain_auth_token fails on `username` keyword when there is no user yet.

### ISSUE THREAD

**Issue by glemmaPaul** [tomchristie/django-rest-framework#2879]
I don't know if this is a Django Rest Framework specific error, but when the Auth User Model uses a different `USERNAME_FIELD` instead of `username` and there are no users created yet it will give the following error saying that it couldn't query on `username` in the database.

## Stack trace
```
Internal Server Error: /api/v1/auth
Traceback (most recent call last):
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/rest_framework/authtoken/views.py", line 17, in post
    serializer.is_valid(raise_exception=True)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/rest_framework/serializers.py", line 186, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/rest_framework/serializers.py", line 367, in run_validation
    value = self.validate(value)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/rest_framework/authtoken/serializers.py", line 16, in validate
    user = authenticate(username=username, password=password)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 60, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/allauth/account/auth_backends.py", line 22, in authenticate
    ret = self._authenticate_by_username(**credentials)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/allauth/account/auth_backends.py", line 37, in _authenticate_by_username
    user = User.objects.get(**query)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/query.py", line 345, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1182, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1120, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1427, in names_to_path
    self.raise_field_error(opts, name)
  File "/Users/pauloostenrijk/.virtualenvs/reservations/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1433, in raise_field_error
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'username' into field. Choices are: auth_token, customer, date_joined, email, first_name, groups, id, is_admin, is_staff, is_superuser, last_login, last_name, logentry, password, providers, reviews, user_permissions
```

After creating a user by running `createsuperuser` the error resolves itself and it works as usual.

The `User` model is as following:
```python
class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_('First name'), max_length=30, blank=True)
    last_name = models.CharField(_('Last name'), max_length=30, blank=True)
    email = models.EmailField(_('Email address'), unique=True, db_index=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('Staff status'), default=False,
                                   help_text=_('Designates whether the user'
                                               ' can log into this admin '
                                               'site.'))
    date_joined = models.DateTimeField(_('Date joined'), default=timezone.now)

    USERNAME_FIELD = 'email'
    objects = UserManager()
```

## More info about setup
Django 1.7.4
Django Rest Framework 3.0.4

**Comment by jpadilla** [comment]
@glemmaPaul this is happening because our serializer [uses](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authtoken/serializers.py#L16) passes username and password to  your authentication backend. It seems you're also using django-allauth's [auth backend](https://github.com/pennersr/django-allauth/blob/master/allauth/account/auth_backends.py#L10) which by looking at your stack trace it's trying to authenticate by username.

Solutions here might be:

- Make sure django-allauth's `AUTHENTICATION_METHOD` is set to only use email or,
- Implement your own serializers/view for auth.
