### ISSUE TITLE
@list_route post cannot return serializer(qs, many=True)

### ISSUE THREAD

**Issue by sainttail** [tomchristie/django-rest-framework#2918]
I have a `@list_route` that look like this

```
@list_route(methods=['post'])
    def test(self, request):
        queryset = self.filter_queryset(self.get_queryset())
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)
```
but when I try to POST to .../events/test/ via browsable API
calling without browsable API is working normally.

I got exactly same error message as #2607 (ListSerializer object is not iterable)

I don't know why this happen? because I want post action to return update objects
However, if i change to this `@list_route(methods=['get'])` or `@list_route(methods=['patch'])` it is working fine

My serializer class is a normal class that extends form ModelSerializer

```
class EventSerializer(serializers.ModelSerializer):
    class Meta:
        model = Event
```

**Comment by tomchristie** [comment]
Could you provide the stack trace you're seeing when you make the POST request?

> but when I try to POST to .../events/test/ via browsable API
> calling without browsable API is working normally.

I didn't understand this - which case works, which case doesn't?

**Comment by sainttail** [comment]
**Here is a stack** trace when I made a POST request via browsable API in web browser
```
Traceback (most recent call last):
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/rest_framework/response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/rest_framework/renderers.py", line 657, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/rest_framework/renderers.py", line 634, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/rest_framework/renderers.py", line 503, in get_rendered_html_form
    [('template', 'rest_framework/api_form.html')]
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/rest_framework/renderers.py", line 357, in render
    return template.render(context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/Users/eak/Desktop/env/sakahama/lib/python2.7/site-packages/django/template/defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'ListSerializer' object is not iterable
```
**Here is a screenshot** when error occurs
![screen shot 2015-05-09 at 1 55 10 am](https://cloud.githubusercontent.com/assets/3015139/7543448/91a6fab6-f5ee-11e4-946e-b9e909c1e4ac.png)

**BUT** It works when I POST via `curl`command
```
curl -X POST -H 'Accept: application/json; indent=4' -u admin:password http://127.0.0.1:8080/api/calendars/test/
```

**Comment by tomchristie** [comment]
> Definitely something wrong with form generate on browsable API because I am returning multiple objects for POST?

Indeed - almost certainly due to the browsable API calling `get_serializer` which by default will not use `many=True` for `POST` requests.

You could resolve this by either:

* Modifying the `get_serializer()` method so that it uses `many=True` for `POST` requests.
* Use `GET` requests for your endpoint instead.

It's possible that we could try to guard against this kind of case more gracefully, but I don't see it as sufficiently worth prioritizing so I'm going to close this off for now.

**Comment by frostli** [comment]
I have the exact same issue; use postman instead to test your api.

**Comment by mikofski** [comment]
@tomchristie I'm trying to modify `get_serializer` for a similar api, but I can't figure it out

* similar to @asedeno
* using POST
* returns multiple objects
* works fine as json, but not as html form in browsable api, I get my ListSerializer is not iterable
* input serializer, a python class object, is not the same as output serializer, a django query set
* I have to use POST because I'm replacing an older API and I'm not allowed to breaking it.

**Comment by khamaileon** [comment]
+1
