### ISSUE TITLE
Imports failing with 3.1.2

### ISSUE THREAD

**Issue by sdawodu** [tomchristie/django-rest-framework#2969]
``` python
>>> import django.conf
>>> django.conf.settings.configure()
>>> import rest_framework.decorators
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 11, in <module>
    from rest_framework.views import APIView
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 14, in <module>
    from rest_framework.response import Response
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/response.py", line 8, in <module>
    from django.utils.six.moves.http_client import responses
ImportError: No module named http_client
>>> import rest_framework
>>> rest_framework.__version__
'3.1.2'
>>> 
```
A normal import which works in 3.1.1 fails in 3.1.2
``` python
>>> import django.conf
>>> django.conf.settings.configure()
>>> import rest_framework.decorators
>>> import rest_framework
>>> rest_framework.__version__
'3.1.1'
```

looking at response.py:

```
 from __future__ import unicode_literals
-from django.core.handlers.wsgi import STATUS_CODE_TEXT
+from django.utils.six.moves.http_client import responses
 from django.template.response import SimpleTemplateResponse
 from django.utils import six
 
@@ -77,7 +77,7 @@ class Response(SimpleTemplateResponse):
         """
         # TODO: Deprecate and use a template tag instead
         # TODO: Status code text for RFC 6585 status codes
-        return STATUS_CODE_TEXT.get(self.status_code, '')
+        return responses.get(self.status_code, '')
 
     def __getstate__(self):
         """
```

``` python
>>> import django.utils.six.moves
>>> import django.utils.six.moves.http_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named http_client
```
So something is missing from django (1.6) utils which is causing rest_framework to break on upgrade. Should this be worked around in rest_framework?

**Comment by tomchristie** [comment]
Looks like this needs to be a little more narrowed down...

`http_client` does exist in 1.6: https://github.com/django/django/blob/1.6/django/utils/six.py#L160

**Comment by sdawodu** [comment]
You are correct. Looks like there might be a problem with loading in django's version of six:

``` python
>>> from django.utils.six.moves.http_client import responses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named http_client
```
but

```
>>> from django.utils.six.moves import http_client
>>> http_client.responses
{200: 'OK', 201: 'Created', 202: 'Accepted', 203: 'Non-Authoritative Information', 204: 'No Content', 205: 'Reset Content', 206: 'Partial Content', 400: 'Bad Request', 401: 'Unauthorized', 402: 'Payment Required', 403: 'Forbidden', 404: 'Not Found', 405: 'Method Not Allowed', 406: 'Not Acceptable', 407: 'Proxy Authentication Required', 408: 'Request Timeout', 409: 'Conflict', 410: 'Gone', 411: 'Length Required', 412: 'Precondition Failed', 413: 'Request Entity Too Large', 414: 'Request-URI Too Long', 415: 'Unsupported Media Type', 416: 'Requested Range Not Satisfiable', 417: 'Expectation Failed', 100: 'Continue', 101: 'Switching Protocols', 300: 'Multiple Choices', 301: 'Moved Permanently', 302: 'Found', 303: 'See Other', 304: 'Not Modified', 305: 'Use Proxy', 306: '(Unused)', 307: 'Temporary Redirect', 500: 'Internal Server Error', 501: 'Not Implemented', 502: 'Bad Gateway', 503: 'Service Unavailable', 504: 'Gateway Timeout', 505: 'HTTP Version Not Supported'}
```

I'm sure this is not intended django behaviour and I'm going to be chasing it up. In the meantime

```
-from django.utils.six.moves.http_client import responses
+from django.utils.six.moves import http_client
 from django.template.response import SimpleTemplateResponse
 from django.utils import six
 
@@ -77,7 +77,7 @@ class Response(SimpleTemplateResponse):
         """
         # TODO: Deprecate and use a template tag instead
         # TODO: Status code text for RFC 6585 status codes
-        return responses.get(self.status_code, '')
+        return http_client.responses.get(self.status_code, '')
 
     def __getstate__(self):
```
This should work around the problem in rest_framework

**Comment by tomchristie** [comment]
@sdawodu Would you be up for issuing a pull request with this fix?

**Comment by xordoquy** [comment]
I'm closing this as it works with Django 1.6.11:

```
bash-3.2$ python
Python 2.7.10 (default, May 25 2015, 13:06:17) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import django.conf
>>> django.conf.settings.configure()
>>> import rest_framework.decorators
>>> from django.utils.six.moves.http_client import responses
>>> exit()
bash-3.2$ pip freeze -l
You are using pip version 6.1.1, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Django==1.6.11
djangorestframework==3.1.2
bash-3.2$ 
```

Feel free to reopen if this issue still happen with Django 1.6.11.
Note that there has been a couple of six upgrades during the 1.6 cycle (https://github.com/django/django/commits/stable/1.6.x/django/utils/six.py) so you should probably upgrade to the latests 1.6.x version (1.6.11 at this time).
