### ISSUE TITLE
UnicodeDecodeError on query search

### ISSUE THREAD

**Issue by gio82** [tomchristie/django-rest-framework#3046]
I have a `ViewSet` with `search_fields`.
When I do a get request with a non ASCII code it give me UnicodeDecodeError.

Example:
`/api/users/?search=cerè`

I got this error:

```
UnicodeDecodeError at /api/users/
'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

Is there something I'm missing or a bug?

**Comment by jpadilla** [comment]
@gio82 A failing test would really help here. Also, what version of Python and DRF?

**Comment by gio82** [comment]
Rigth!

```
UnicodeDecodeError at /api/users/
'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Request Method:	GET
Request URL:	http://localhost:8000/api/users/?search=cer%C3%A8
Django Version:	1.8.1
Exception Type:	UnicodeDecodeError
Exception Value:	
'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Exception Location:	/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py in quote, line 1283
Python Executable:	/venv/bin/python
Python Version:	2.7.6
Python Path:	
['/WebPortal',
 '/venv/lib/python27.zip',
 '/venv/lib/python2.7',
 '/venv/lib/python2.7/plat-darwin',
 '/venv/lib/python2.7/plat-mac',
 '/venv/lib/python2.7/plat-mac/lib-scriptpackages',
 '/venv/Extras/lib/python',
 '/venv/lib/python2.7/lib-tk',
 '/venv/lib/python2.7/lib-old',
 '/venv/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/venv/lib/python2.7/site-packages',
 '/WebPortal']
Server time:	Gio, 18 Giu 2015 10:19:05 +0200
```

**Comment by gio82** [comment]
DRF 3.1

**Comment by jpadilla** [comment]
@gio82 is that a full traceback? I just tried the following in our `SearchFilterTests` and it passed.

```python
    def test_exact_search_unicodedecodeerror(self):
        obj = SearchFilterModel.objects.create(title='cerè', text='cde')

        class SearchListView(generics.ListAPIView):
            queryset = SearchFilterModel.objects.all()
            serializer_class = SearchFilterSerializer
            filter_backends = (filters.SearchFilter,)
            search_fields = ('=title', 'text')

        view = SearchListView.as_view()
        request = factory.get('/', {'search': 'cerè'})
        response = view(request)
        self.assertEqual(
            response.data,
            [
                {'id': obj.id, 'title': obj.title, 'text': obj.text}
            ]
        )
```

**Comment by gio82** [comment]
```
/venv/lib/python2.7/site-packages/rest_framework/templatetags/rest_framework.py in add_query_param
                return escape(replace_query_param(uri, key, val)) ...
▶ Local vars
/venv/lib/python2.7/site-packages/rest_framework/utils/urls.py in replace_query_param
                query = urlparse.urlencode(sorted(list(query_dict.items())), doseq=True) ...
▶ Local vars
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py in urlencode
                                    l.append(k + '=' + quote_plus(str(elt))) ...
▶ Local vars
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py in quote_plus
                return quote(s, safe) ...
▶ Local vars
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py in quote
                if not s.rstrip(safe): ...
▶ Local vars
```

Is there an easier way to share the whole debug page?

**Comment by xordoquy** [comment]
I think you have a link at the page bottom to send the traceback to dpaste

**Comment by gio82** [comment]
Not able to see that button...

![screen shot 2015-06-18 at 14 44 42](https://cloud.githubusercontent.com/assets/3081584/8231424/c13aeba8-15c8-11e5-9c03-0817a4749abc.png)

**Comment by jpadilla** [comment]
@gio82 in that case, the full traceback should also probably be in the terminal.

P.S. If you haven't looked into `django-extensions` + `werkzeug` for dev, check it out.

**Comment by gio82** [comment]
Nope, in the terminal I just have: `[18/Jun/2015 14:41:50]"GET /api/users/?search=cer%C3%A8 HTTP/1.1" 500 318356`

This is running the api in debug via web interface:

![screen shot 2015-06-18 at 14 54 18](https://cloud.githubusercontent.com/assets/3081584/8231634/31f21244-15ca-11e5-8018-eaed332abdd3.png)


And this is in production `debug=False` in the email django send me:

```
Internal Server Error: /api/users/
Traceback (most recent call last):
 File "/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
   return view_func(*args, **kwargs)
 File "/venv/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
   return self.dispatch(request, *args, **kwargs)
 File "/venv/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
   response = self.handle_exception(exc)
 File "/venv/lib/python2.7/site-packages/rest_framework/views.py", line 440, in dispatch
   self.initial(request, *args, **kwargs)
 File "/venv/lib/python2.7/site-packages/rest_framework/views.py", line 354, in initial
   self.perform_authentication(request)
 File "/venv/lib/python2.7/site-packages/rest_framework/views.py", line 292, in perform_authentication
   request.user
 File "/venv/lib/python2.7/site-packages/rest_framework/request.py", line 491, in __getattribute__
   return super(Request, self).__getattribute__(attr)
 File "/venv/lib/python2.7/site-packages/rest_framework/request.py", line 266, in user
   self._authenticate()
 File "/venv/lib/python2.7/site-packages/rest_framework/request.py", line 454, in _authenticate
   user_auth_tuple = authenticator.authenticate(self)
 File "/venv/lib/python2.7/site-packages/oauth2_provider/ext/rest_framework/authentication.py", line 18, in authenticate
   valid, r = oauthlib_core.verify_request(request, scopes=[])
 File "/venv/lib/python2.7/site-packages/oauth2_provider/oauth2_backends.py", line 135, in verify_request
   valid, r = self.server.verify_request(uri, http_method, body, headers, scopes=scopes)
 File "/venv/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
   return f(endpoint, uri, *args, **kwargs)
 File "/venv/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 68, in verify_request
   request = Request(uri, http_method, body, headers)
 File "/venv/lib/python2.7/site-packages/oauthlib/common.py", line 389, in __init__
   self.headers = CaseInsensitiveDict(encode(headers or {}))
 File "/venv/lib/python2.7/site-packages/oauthlib/common.py", line 385, in <lambda>
   encode = lambda x: to_unicode(x, encoding) if encoding else x
 File "/venv/lib/python2.7/site-packages/oauthlib/common.py", line 331, in to_unicode
   return dict(((to_unicode(k, encoding), to_unicode(v, encoding)) for k, v in data))
 File "/venv/lib/python2.7/site-packages/oauthlib/common.py", line 331, in <genexpr>
   return dict(((to_unicode(k, encoding), to_unicode(v, encoding)) for k, v in data))
 File "/venv/lib/python2.7/site-packages/oauthlib/common.py", line 317, in to_unicode
   return unicode_type(data, encoding=encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 10: unexpected end of data

Request repr(): 
<WSGIRequest
path:/api/users/,
GET:<QueryDict: {u'search': [u'Cer\xe8']}>,
POST:<QueryDict: {}>,
COOKIES:{},
....
```

**Comment by jpadilla** [comment]
I think this isn't a problem on our side. See the last line on the traceback.

```
 File "/venv/lib/python2.7/site-packages/oauthlib/common.py", line 317, in to_unicode
   return unicode_type(data, encoding=encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 10: unexpected end of data
```

**Comment by xordoquy** [comment]
I'm going to close this as this appears to be linked with oauthlib / oauth2_provider.
