### ISSUE TITLE
`allow_empty` does not work on serializers with `many=True`.

### ISSUE THREAD

**Issue by pmdarrow** [tomchristie/django-rest-framework#3361]
Is this expected behaviour?

```python
>>> from rest_framework import serializers
>>>
>>> class ChildSerializer(serializers.Serializer):
...     name = serializers.CharField()
...
>>> class ParentSerializer(serializers.Serializer):
...     children = ChildSerializer(many=True, allow_empty=False)
...
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<console>", line 2, in ParentSerializer
  File "/Users/pmdarrow/.virtualenvs/api/lib/python3.4/site-packages/rest_framework/serializers.py", line 96, in __new__
    return cls.many_init(*args, **kwargs)
  File "/Users/pmdarrow/.virtualenvs/api/lib/python3.4/site-packages/rest_framework/serializers.py", line 116, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/Users/pmdarrow/.virtualenvs/api/lib/python3.4/site-packages/rest_framework/serializers.py", line 90, in __init__
    super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'allow_empty'
```

**Comment by xordoquy** [comment]
allow_empty isn't part of the field's core arguments as listed in the [documentation](http://www.django-rest-framework.org/api-guide/fields/) so I'd expect allow_empty will raise an exception.
Do you have a use case where this should be a required argument ?

**Comment by pmdarrow** [comment]
It's the same use case for `allow_empty` on a `ListField`. In my example I want to disallow an empty list for `children`.

**Comment by xordoquy** [comment]
Alright, looks legit. PR to come.

**Comment by pmdarrow** [comment]
:+1:
