### ISSUE TITLE
Is CursorPagination ready? CursorPagination + GeoDjango problem

### ISSUE THREAD

**Issue by grapemix** [tomchristie/django-rest-framework#3472]
I was wondering if the CursorPagination is ready. If not, please ignore the following. Is CursorPagination suppose to work if GeoDjango, if not, please ignore.

I was trying out the CursorPagination together with geoDjango for my current API. But every new stuff needs some tester, right? Right now, I am using PageNumberPagination in my API with no problem.
Here is my model:

```python
class Spot(models.Model):
  some_id_in_another_db_model = models.IntegerField()
  loc = models.PointField(
      null=True,
      blank=True,
      )
  objects = models.GeoManager()
```

And here is my sample query:

```python
f= {}
pt = Point(123, 123, srid=4326)
f["loc__distance_lte"]=(pt, D(mi=q["distance"]))
Spot.objects.filter(**f).distance(pt).order_by("distance")
```

I am sure the queryset is fine and return valid result.

Here is my traceback:

```python
Traceback (most recent call last):
  File "/home/cry/palila/app/api/tests/testAPI.py", line 394, in testFxnName
    **self.loginHeader
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/rest_framework/views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/rest_framework/views.py", line 448, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 41, in list
    page = self.paginate_queryset(queryset)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/rest_framework/generics.py", line 170, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/cry/palila/app/api/paginator.py", line 84, in paginate_queryset
    view
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/rest_framework/pagination.py", line 532, in paginate_queryset
    queryset = queryset.filter(**kwargs)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1304, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1332, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1173, in build_filter
    self.check_related_objects(field, value, opts)
  File "/opt/crystal/venv/palila/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1058, in check_related_objects
    if field.rel:
AttributeError: 'DistanceField' object has no attribute 'rel'
```

**Comment by tomchristie** [comment]
> I was wondering if the CursorPagination is ready.

Yes.

> Is CursorPagination suppose to work if GeoDjango.

Not something that's been considered. If you can reduce this to a simpler example case that demonstrates a root problem then we'd consider it, but as it stands this isn't something worth us putting time into ourselves.
