### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'view_name'

### ISSUE THREAD

**Issue by SalahAdDin** [tomchristie/django-rest-framework#3688]
I did the HiperlinkedSerializer tutorial for get the objects child from a object and i get this error.

I delete de view_name and it works! I think that your documentation are deprecated, please, update it.

**Comment by xordoquy** [comment]
Thanks for the report. Unfortunately there isn't much informations here. Where / what line does the issue occur, what is the full backtrace ?

**Comment by dimitrovskif** [comment]
As far as I know, only hyperlinked relational **FIELDS** can use the `view_name` argument. I suppose you are using it as a serializer constructor (ex. `YourSerializer(view_name='your_view_name')`) and that causes the problem.

**Comment by SalahAdDin** [comment]
I was doing all as are in the tutorial:

```bash

  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/maqam/urls.py", line 24, in <module>
    url(r'^music/', include('music.urls')),
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/urls.py", line 4, in <module>
    from .views import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/views.py", line 2, in <module>
    from .serializers import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 36, in <module>
    class StaffSerializer(serializers.HyperlinkedModelSerializer):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 39, in StaffSerializer
    many=True, read_only=False, view_name='staff-notes',
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 101, in __new__
    return cls.many_init(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 122, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 95, in __init__
    super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'view_name'
[01/Dec/2015 15:33:51] "GET /music/api/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/maqam/urls.py", line 24, in <module>
    url(r'^music/', include('music.urls')),
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/urls.py", line 4, in <module>
    from .views import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/views.py", line 2, in <module>
    from .serializers import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 36, in <module>
    class StaffSerializer(serializers.HyperlinkedModelSerializer):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 39, in StaffSerializer
    many=True, read_only=False, view_name='staff-notes',
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 101, in __new__
    return cls.many_init(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 122, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 95, in __init__
    super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'view_name'
[01/Dec/2015 15:33:52] "GET /music/api/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/maqam/urls.py", line 24, in <module>
    url(r'^music/', include('music.urls')),
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/urls.py", line 4, in <module>
    from .views import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/views.py", line 2, in <module>
    from .serializers import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 36, in <module>
    class StaffSerializer(serializers.HyperlinkedModelSerializer):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 39, in StaffSerializer
    many=True, read_only=False, view_name='staff-notes',
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 101, in __new__
    return cls.many_init(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 122, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 95, in __init__
    super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'view_name'
[01/Dec/2015 15:33:53] "GET /music/api/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/maqam/urls.py", line 24, in <module>
    url(r'^music/', include('music.urls')),
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/urls.py", line 4, in <module>
    from .views import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/views.py", line 2, in <module>
    from .serializers import *
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 36, in <module>
    class StaffSerializer(serializers.HyperlinkedModelSerializer):
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/maqam/music/serializers.py", line 39, in StaffSerializer
    many=True, read_only=False, view_name='notes-detail',
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 101, in __new__
    return cls.many_init(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 122, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/media/tulipanrog/Data/Proyectos/Universidad/Moviles/Aplicacion/server/lib/python3.4/site-packages/rest_framework/serializers.py", line 95, in __init__
    super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'view_name'

```

**Comment by xordoquy** [comment]
What about the code sample. Names are different from the tutorial so your context is different.

**Comment by xordoquy** [comment]
Let's move this to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) which is the best place to take this discussion. Thanks!

**Comment by xordoquy** [comment]
@dimitrovskif thanks for your comment, I think you got the point.

**Comment by SalahAdDin** [comment]
Isn't it, it's the same context, I used HyperLinked model serializer for my serializer, and use the same commands in the tutorial, so, shell says me that view_name it's a wrong parameter, or... i have create a view, but in the tutorial doesn't say me this.

I think that the tutorial are outdate.

**Comment by xordoquy** [comment]
@SalahAdDin Most of the issues stating people were following the tutorial and it wasn't working were in fact small changes from user that broke things. So unless you can point me where the tutorial fails I won't consider it an issue. If you want help to understand what doesn't work in your case please use the discussion group (linked provided in a previous comment).

**Comment by dimitrovskif** [comment]
1. While some parts in DRF change, the hyperlinked fields are consistent with the docs, and the tutorial is *not* outdated. 
2. Please send us a small test that produces the error. Or at least paste line 30 to 50 in `maqam/music/serializers.py` 
3. Clarify the DRF version you are using.

**Comment by SalahAdDin** [comment]
30 to 50? These file hasn't all these lines:

```python
from .models import *
from rest_framework import serializers


class NoteSerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = Note
        fields = ('id', 'name', 'type', 'note', 'acoustic_index', 'accidental', 'dots', 'duration', 'get_keys', 'staff', )


class StaffSerializer(serializers.HyperlinkedModelSerializer):

    """
    notes = serializers.HyperlinkedModelSerializer(
        many=True, read_only=False,     # view_name='notes-detail',
    )
    """

    class Meta:
        model = Staff
        fields = ('id', 'clef', 'notes', )


class MakamSerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = Makam
        fields = ('id', 'name', 'description', 'staff', 'slug')


class SheetMusicSerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = SheetMusic
        fields = ('id', 'title', 'author', 'instrument_type', 'instrument', 'description', 'type', 'staff', 'slug')

```

I have the lastest DRF version, i know because i installed it one week ago.

**Comment by xordoquy** [comment]
@SalahAdDin You're not helping since your traceback says you have an issue on line 36 and 39 in music/serializers.py

Now please move this discussion to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework). The issue tracker isn't a support forum.

**Comment by tomchristie** [comment]
(Sorry wrong button)

**Comment by erayerdin** [comment]
Alright, so, I have no intentions to reopen this issue, but I found this on Google, solved the problem afterwards and my solution might help any Googlers out there.

First off, I did this with `pk` of my model. It seems the `kwarg` on the URL *must correspond* a field on your model. Every model has a property called `pk`, so I didn't have any problem.

Also, instead of using `extra_kwargs` as @SalahAdDin mentioned here, I looked a bit below of [the same part](http://www.django-rest-framework.org/api-guide/serializers/#how-hyperlinked-views-are-determined) of the documentation, which suggests an alternative that is to use fields *explicitly*. The related URL is as below:

    path("ajax/foo/<int:pk>/", views.FooCRUDAJAXView.as_view(), name="ajax-foo") # Django 2.0 URL

As you can see, it has a field called `pk` which is type of `int`. `pk` field is also present in my model as well.

And my serializer goes like:

    class ContactSerializer(serializers.HyperlinkedModelSerializer):
        id = serializers.HyperlinkedIdentityField(
            view_name="ajax-foo", # view's name
            lookup_field="pk", # the field which is the same in both ajax-foo URL and Foo model
            read_only=True # I needed this in my case
        )

        class Meta:
            model = models.Foo
            fields = ("id", "bar", "baz")

As you can see, URL's lookup field and model's property must be the same.

I used this in a `ListAPIView`, so might not work in your case. Change it to your needs.
