### ISSUE TITLE
Errors when using django-taggit + django-rest-swagger

### ISSUE THREAD

**Issue by john2x** [tomchristie/django-rest-framework#3770]
I have a ModelSerializer for a model that has a `TaggableManager` field named `tags`. In this ModelSerialzer, the `tags` field is *not* listed in the `Meta.fields` of the serializer class.

But when using the docs UI of django-rest-swagger, I'm getting:

    Internal Server Error: /api-docs/api-docs/api/foo
    Traceback (most recent call last):
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
        return view_func(*args, **kwargs)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
        return self.dispatch(request, *args, **kwargs)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
        response = self.handle_exception(exc)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
        response = handler(request, *args, **kwargs)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework_swagger/views.py", line 152, in get
        'models': generator.get_models(apis),
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 122, in get_models
        self._find_field_serializers(serializers)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 260, in _find_field_serializers
        fields = serializer().get_fields()
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 918, in get_fields
        info = model_meta.get_field_info(model)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework/utils/model_meta.py", line 69, in get_field_info
        reverse_relations = _get_reverse_relationships(opts)
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework/utils/model_meta.py", line 144, in _get_reverse_relationships
        to_field=_get_to_field(relation.field),
      File "/var/www/myapp/venv/local/lib/python2.7/site-packages/rest_framework/utils/model_meta.py", line 95, in _get_to_field
        return field.to_fields[0] if field.to_fields else None
    AttributeError: 'TaggableManager' object has no attribute 'to_fields'
    [23/Dec/2015 10:44:52] "GET /api-docs/api-docs/api/foo HTTP/1.1" 500 124349

I tried changing the `_get_to_field` utility function to:

```
def _get_to_field(field):
    if not hasattr(field, 'to_fields'):
        return None
    return field.to_fields[0] if field.to_fields else None
```

and it works around the issue, but still need to verify if it doesn't break anything else.

**Comment by xordoquy** [comment]
I don't agree with that fix.
The `_get_to_fields` is called on fields that are identified as 'simple' forward relation (direct `ForeignKey`).
`TaggalbeManager` should be more like `ManyToMany` though it doesn't seem to be listed in the `many_to_many` list.
To me the root cause would be to figure out why it isn't considered as a many to many field.

**Comment by auvipy** [comment]
you could use django-rest-taggit

**Comment by john2x** [comment]
@auvipy do you mean [django-taggit-serializer](https://github.com/glemmaPaul/django-taggit-serializer)? 

@xordoquy It looks like [`TaggableManager`][3] does not inherit from Django's `ManyToMany` field. It has `many_to_many` set to `True`, but it seems Django's [`get_all_related_objects`][1] and [`get_all_related_many_to_many_objects`][2] methods only care about fields that are instances of `ManyToMany` (ignores the `many_to_many` property).

What about updating the `_get_forward_relationships` method to use `_get_fields` instead (if available, and since the `get_all_related_*` methods are deprecated) and explicitly check for the `many_to_many` property of a field like so:

```python
def _get_reverse_relationships(opts):
    """
    Returns an `OrderedDict` of field names to `RelationInfo`.
    """
    # Note that we have a hack here to handle internal API differences for
    # this internal API across Django 1.7 -> Django 1.8.
    # See: https://code.djangoproject.com/ticket/24208

    reverse_relations = OrderedDict()
    fields = opts._get_fields(forward=False, reverse=True, include_parents=False)
    related_objects = [f for f in fields if f.field.many_to_many is False]
    related_many_to_many_objects = [f for f in fields if f.field.many_to_many is True]
    for relation in related_objects:
        accessor_name = relation.get_accessor_name()
        related = getattr(relation, 'related_model', relation.model)
        reverse_relations[accessor_name] = RelationInfo(
            model_field=None,
            related_model=related,
            to_many=relation.field.rel.multiple,
            to_field=_get_to_field(relation.field),
            has_through_model=False
        )

    # Deal with reverse many-to-many relationships.
    for relation in related_many_to_many_objects:
        accessor_name = relation.get_accessor_name()
        related = getattr(relation, 'related_model', relation.model)
        reverse_relations[accessor_name] = RelationInfo(
            model_field=None,
            related_model=related,
            to_many=True,
            # manytomany do not have to_fields
            to_field=None,
            has_through_model=(
                (getattr(relation.field.rel, 'through', None) is not None) and
                not relation.field.rel.through._meta.auto_created
            )
        )

    return reverse_relations
```

[1]: https://github.com/django/django/blob/1.9/django/db/models/options.py#L617
[2]: https://github.com/django/django/blob/1.9/django/db/models/options.py#L645
[3]: https://github.com/alex/django-taggit/blob/develop/taggit/managers.py#L274-L276

**Comment by xordoquy** [comment]
I don't know what's the exact status for the many_to_many flag since the Meta refactoring from Daniel Pyrathon.

**Comment by tomchristie** [comment]
I'm inclined to pass the buck on this one, unless we see a ticket that isolates the problem to REST framework.
