### ISSUE TITLE
Cryptic error message from serializers.py

### ISSUE THREAD

**Issue by flyingcircle** [tomchristie/django-rest-framework#3882]
Alright I've been trying to figure out this issue for some time now, but it is just far too cryptic to me. I tried copying down almost word for word from the setup guide.

Django - 1.9.1
rest_framework - 3.3.2
python 2.7.3

Internal Server Error: /api/v1/tasks/
Traceback (most recent call last):
  File "/home/sas/sas/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sas/sas/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/sas/sas/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/renderers.py", line 675, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/renderers.py", line 617, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/renderers.py", line 540, in get_raw_data_form
    content = renderer.render(serializer.data, accepted, context)
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/serializers.py", line 503, in data
    ret = super(Serializer, self).data
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/serializers.py", line 243, in data
    self._data = self.get_initial()
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/serializers.py", line 386, in get_initial
    for field in self.fields.values()
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/serializers.py", line 339, in fields
    for key, value in self.get_fields().items():
  File "/home/sas/sas/lib/python2.7/site-packages/rest_framework/serializers.py", line 949, in get_fields
    fields[field_name] = field_class(**field_kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)

urls.py:
urlpatterns = [
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
]

routers.py
router = routers.DefaultRouter()

from #########.tasks.api import TasksViewSet
router.register(r'tasks', TasksViewSet, base_name="tasks")

tasks/api.py
from rest_framework import serializers
from rest_framework import viewsets
from rest_framework.response import Response

from .models import Task

class TaskSerializer(serializers.ModelSerializer):
    class Meta:
        model = Task
        fields = ("id", "type", "file", "###########", "###########",
                  "priority", "submit_time", "submitter_email", "status")

class TasksViewSet(viewsets.ModelViewSet):
    """
    Viewset to add/view tasks.
    """
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

**Comment by xordoquy** [comment]
Somehow you use a field either defined explicitly on `TaskSerializer` or on the `Task` model that isn't compatible with Django REST framework.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by flyingcircle** [comment]
Found out that this was related to issue #3520. Would have been nice to have been told what field was the issue instead of having eliminate one-by-one.

**Comment by xordoquy** [comment]
@flyingcircle you could have had that with pdb or an equivalent.
