### ISSUE TITLE
APITestCase Format Error when format='html'

### ISSUE THREAD

**Issue by sidja** [tomchristie/django-rest-framework#3923]
I am getting the following error for the below test case 

I've used the recommended settings in settings.py 

Is there anything I am missing ? 

test.py
			class BoardTests(APITestCase):
				
			
				def test_board_list(self):
			
					url = reverse('boards')
					data = {'name': 'TestCreateBoard','description':'TestDescription'}
					response = self.client.post(url, data, format='html')
					self.assertIn(response.content, 'TestCreateBoard')

settings.py 

        REST_FRAMEWORK = {
            
            'TEST_REQUEST_RENDERER_CLASSES': (
                'rest_framework.renderers.MultiPartRenderer',
                'rest_framework.renderers.JSONRenderer',
                'rest_framework.renderers.TemplateHTMLRenderer'
            )
        }

Error Text

      ======================================================================
      ERROR: test_board_list (app.tests.BoardTests)
      ----------------------------------------------------------------------
      Traceback (most recent call last):
        File "/home/sid/code/interview_tests/stitch/workspace/trello/app/tests.py", line 32, in test_board_list
          response = self.client.post(url, data, format='html')
        File "/home/sid/.virtualenvs/stitch/local/lib/python2.7/site-packages/rest_framework/test.py", line 170, in post
          path, data=data, format=format, content_type=content_type, **extra)
        File "/home/sid/.virtualenvs/stitch/local/lib/python2.7/site-packages/rest_framework/test.py", line 91, in post
          data, content_type = self._encode_data(data, format, content_type)
        File "/home/sid/.virtualenvs/stitch/local/lib/python2.7/site-packages/rest_framework/test.py", line 66, in _encode_data
          ret = renderer.render(data)
        File "/home/sid/.virtualenvs/stitch/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 161, in render
          view = renderer_context['view']
      KeyError: u'view'
      
      ----------------------------------------------------------------------
      Ran 2 tests in 0.009s

**Comment by xordoquy** [comment]
@sidja Did you manage to find the issue ? If so, mind sharing ?

**Comment by sidja** [comment]
Sorry, this is a non issue, I was using a POST instead of GET. Thank you for looking into it.

**Comment by xordoquy** [comment]
Thanks for the feedback.
