### ISSUE TITLE
RelatedManager saving values in Django-1.9 fails

### ISSUE THREAD

**Issue by tarvitz** [tomchristie/django-rest-framework#4057]
I've faced with issue with creating nested instances inside ``rest_framework.serializer.serializers.ModelSerializer.create`` with following traceback

```python
Traceback (most recent call last):
  File "/home/nfox/code/drf_relatedmanager_bug/relations/tests.py", line 19, in test_create_person_with_friends
    format='json')
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/test.py", line 169, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/test.py", line 91, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/test/client.py", line 380, in generic
    return self.request(**r)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/test.py", line 158, in request
    return super(APIClient, self).request(**kwargs)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/test.py", line 110, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/test/client.py", line 467, in request
    six.reraise(*exc_info)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/serializers.py", line 192, in save
    self.instance = self.create(validated_data)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/serializers.py", line 872, in create
    related_manager_setter(instance, field_name, value)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/src/djangorestframework/rest_framework/compat.py", line 192, in _related_manager_setter
    setattr(instance, field_name, value)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 481, in __set__
    manager.set(value)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 662, in set
    self.add(*objs, bulk=bulk)
  File "/home/nfox/code/drf_relatedmanager_bug/.tox/py35-django19/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 568, in add
    "the object first." % obj
ValueError: <Contact: Matrix> instance isn't saved. Use bulk=False or save the object first.
```

## Steps to reproduce
Here's small example how to reproduce the bug. Simply use replace git import with djangorestframework==3.3.3 inside requirements/base.txt and run tox:

https://github.com/tarvitz/drf_relatedmanager_bug

## Expected behavior

Expected to be working fine

## Actual behavior

Trackback fall using application with django19 and python-2.7, python-3.4, python-3.5
With django-1.8 it working well.

I've also implement dirty hotfx you can find here: https://github.com/tarvitz/django-rest-framework/commit/db61c090cf2ed538ad033421336d44e9054247ed

**Comment by xordoquy** [comment]
Writable nested serializers aren't supported out of the box as mentioned in the [documentation](http://www.django-rest-framework.org/api-guide/relations/#writable-nested-serializers).
Reason is DRF can't figure the save order for all the possible combinations therefore you'll have to explicitly perform the create/update.
