### ISSUE TITLE
__init__() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by KhaledElAnsari** [tomchristie/django-rest-framework#4069]
Hello, I'm having a problem with djangorest

when i runserver everything looks fine but when I open the browser I get this

```
Internal Server Error: /
Traceback (most recent call last):
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/utils.py", line 86, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/rest_framework/renderers.py", line 674, in render
    template = loader.get_template(self.template)
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/loader.py", line 26, in get_template
    engines = _engine_list(using)
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/utils.py", line 110, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/home/khaled/Desktop/Sites/POSRocket/internal-api/env/lib/python3.4/site-packages/django/template/backends/django.py", line 33, in __init__
    self.engine = Engine(self.dirs, self.app_dirs, **options)
TypeError: __init__() got an unexpected keyword argument 'timeout'
```

I can't see anything! please help me

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by tomchristie** [comment]
Looks like you've got an invalid configuration for in your DB settings or something similar.
In any case, this isn't a bug in REST framework. Probably best to try the [Django Users](https://groups.google.com/forum/#!forum/django-users) google group.

**Comment by KhaledElAnsari** [comment]
Thank you people and sorry for bothering you

**Comment by tomchristie** [comment]
No problem at all - best of luck tracking it down!
