### ISSUE TITLE
CONTRIBUTING.md instructions incomplete

### ISSUE THREAD

**Issue by cdman** [tomchristie/django-rest-framework#4572]
[CONTRIBUTING.md](https://github.com/tomchristie/django-rest-framework/blob/master/CONTRIBUTING.md) gives the following instructions:

> To run the tests, clone the repository, and then:
> 
>     # Setup the virtual environment
>     virtualenv env
>     source env/bin/activate
>     pip install -r requirements.txt
> 
>     # Run the tests
>     ./runtests.py

However doing these steps does not install Django, and it will result in the following error output:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/env/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/env/local/lib/python2.7/site-packages/_pytest/config.py", line 839, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/env/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/env/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/env/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/env/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/gpanther/greypanther/django-rest-framework/tests/conftest.py", line 2, in pytest_configure
INTERNALERROR>     from django.conf import settings
INTERNALERROR> ImportError: No module named django.conf
```

Either the file should mention that Django needs to be pip installed-ed, or Django needs to be added into one of the requirements file.

**Comment by tomchristie** [comment]
Good call, yup. You're welcome to submit a pull request for that, or we can add it ourselves. (Either is fine!) 😄

**Comment by cdman** [comment]
@tomchristie - will submit a PR shortly.

**Comment by cdman** [comment]
Thank you @akshaysharma096 for implementing this!
