### ISSUE TITLE
Breaks in Python3.6

### ISSUE THREAD

**Issue by cnobile2012** [tomchristie/django-rest-framework#4771]
## This may not be a big issue yet, but when I tried to run my tests in Travis it broke in DRF on Python3.6.

```
  The command "(cd inventory/settings/; ln -s travis.py local.py)" exited with 0.
  1.07s$ python manage.py makemigrations accounts categories invoices locations projects regions suppliers
  Traceback (most recent call last):
    File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/rest_framework/settings.py", line 177, in import_from_string module = importlib.import_module(module_path)
    File "/home/travis/virtualenv/python3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 978, in _gcd_import
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
    File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/rest_framework_xml/parsers.py", line 13, in <module>
      from .compat import etree
    File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/rest_framework_xml/compat.py", line 9, in <module>
      import defusedxml.ElementTree as etree
    File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 62, in <module>
      _XMLParser, _iterparse, _IterParseIterator, ParseError = _get_py3_cls()
    File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 56, in _get_py3_cls
      _IterParseIterator = pure_pymod._IterParseIterator
  AttributeError: module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'
```

**Comment by rpkilby** [comment]
btw - this seems to originate from `rest_framework_xml`, not DRF itself.

**Comment by kevin-brown** [comment]
The XML parser and renderer are available as part of the [django-rest-framework-xml](https://github.com/jpadilla/django-rest-framework-xml) package, which does not appear to be tested on Python 3.6. With that being said, this appears to be an issue with the [defusedxml](https://pypi.python.org/pypi/defusedxml) package, which hasn't been updated for a couple of years.

So, I'm going to close off this ticket as the issue appears to be within a downstream project. I'd recommend filing a ticket with defusedxml about Python 3.6 support and/or django-rest-framework-xml about finding a more up-to-date XML library.
